### ISSUE TITLE
Include a toggle link on the menu sidebar to collapse/expand the width

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mRMS#368]
When collapsed, only the menu icons display. When expanded, the icons with corresponding text display.

**Comment by bluenevus** [comment]
well really we want it redesigned so it more like teams 
![image](https://user-images.githubusercontent.com/3675043/121613984-b55b5c00-ca2b-11eb-88fa-34897e2b5a1b.png)

**Comment by bluenevus** [comment]
so you can imagine this 
![image](https://user-images.githubusercontent.com/3675043/121614250-4c281880-ca2c-11eb-85e6-6e2b7e5b28a2.png)

will be the little icons on the far left all the time because there will be no more icons there

on click you get the menu you see in APPS above that lists all the report channels available in the personal, group or public report

![image](https://user-images.githubusercontent.com/3675043/121614319-6cf06e00-ca2c-11eb-834a-dfa238168fab.png)

then in the main window you have cards representing all the data sets you have there like so 
![image](https://user-images.githubusercontent.com/3675043/121614377-87c2e280-ca2c-11eb-99e4-0744224f58e7.png)

**Comment by bluenevus** [comment]
see this issue https://github.com/MicroHealthLLC/mRMS/issues/399.  we probably need a mockup @LAlexMHllc
