### ISSUE TITLE
Include ability to Delete a user before the set elapsed restore time.

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mRMS#431]
Screenshot Example of User table

![users_confirm_delete](https://user-images.githubusercontent.com/11938477/120500605-fc43b480-c38e-11eb-9955-6f06464bd05f.png)

Would some of these fields need to be updated, even temporarily?
Screenshot Example of SETTINGS - Authentication tab

![settings_authentication](https://user-images.githubusercontent.com/11938477/120500661-0665b300-c38f-11eb-9d93-f3a089df6422.png)

**Comment by b-solution** [comment]
@LAlexMHllc Right now we are only soft deleting the user, that is why restore icon display because we can restore it. 
It exists in Data Base but act like it does not, except one thing that we cannot create new user with same email.

My suggestion is that we add multiple tabs like, 'User', 'Active User', 'Audit User', 'Deleted User'. All soft deleted users came under deleted user tab. We can restore it from this tab OR If we really want to remove a user from our Data Base we can delete it from deleted user tab and it will completely destroyed from our DB.

It's all up to you how you want to handle this scenario.

**Comment by bluenevus** [comment]
sounds good on your suggestion

**Comment by LAlexMHllc** [comment]
Would like Confirm Delete to include checkbox with label "Permanently Delete". 
- When unchecked (default) and OK clicked, the user can be restored.
- When checked and OK clicked, the user will be permanently deleted from DB. 

Screenshot Example

![user_delete_modal](https://user-images.githubusercontent.com/11938477/120663062-b272d100-c457-11eb-9379-2b4b5c2dbb60.png)

**Comment by LAlexMHllc** [comment]
Closing, fixed
Screenshot Example

![confirm_delete_user](https://user-images.githubusercontent.com/11938477/121572986-bae88000-c9f2-11eb-9d6b-0affdc2f79cf.png)
