### ISSUE TITLE
reports are still not sizing right

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mRMS#499]
the report looks like this with scroll bars at 1080p

![image](https://user-images.githubusercontent.com/3675043/123337782-bdc89200-d515-11eb-9789-d85e56c433df.png)

The maximize looks right though

the dashboard still has the scroll and now its missing the maximize for individual reports
![image](https://user-images.githubusercontent.com/3675043/123337953-fd8f7980-d515-11eb-85ad-c4e29d86855e.png)

Tables seem too look right though

**Comment by bluenevus** [comment]
If I zoom out to 67% then it looks like this with vertical scroll bars now

![image](https://user-images.githubusercontent.com/3675043/123338060-37f91680-d516-11eb-957f-698d855abb90.png)

**Comment by bluenevus** [comment]
report cuts of names

![image](https://user-images.githubusercontent.com/3675043/123818084-b105be80-d8c6-11eb-83b9-8c621b52cabc.png)

**Comment by b-solution** [comment]
@bluenevus 
In dashboard we split the screen into half to display 2 reports per row. So, when we click on maximise button it always display on half of the screen and we should redirect it again to make the report to cover full screen. I remove maximise button because we can achieve same thing by clicking on title of the report. That is why we do not need maximise button in dashboard. we can open the report by clicking on title of the report and it will redirect us to report display page.

If you still need this to cover we must think of some other solution or display one report per row to cover entire screen on maximise. Please share your opinion, thanks.
