### ISSUE TITLE
Public Channel - Clicked "Connect with Dashboards" button and an error screen displayed

### ISSUE THREAD

**Issue by LAlexMHllc** [MicroHealthLLC/mRMS#517]
Screenshot Example

![public_channel_clicked_connect_dashboards_button_error_screen_displayed](https://user-images.githubusercontent.com/11938477/124162486-7f2e5c80-da6c-11eb-9540-e19b89dbc118.png)

**Comment by b-solution** [comment]
@LAlexMHllc Currently I'm not able to produce this issue. Can you check it again. if this issue still exists provide me some info to figure this out.

**Comment by LAlexMHllc** [comment]
Example Screenshots of clicks to get to Not Authorized screen

![click_1_to_view_data_set](https://user-images.githubusercontent.com/11938477/124622380-0e5eba00-de49-11eb-811c-2a6133504b1c.png)

![click_2_to_view_report](https://user-images.githubusercontent.com/11938477/124622391-13236e00-de49-11eb-9f7f-cea63e7851a7.png)

![click_3_connect_with_dashboards_button](https://user-images.githubusercontent.com/11938477/124622409-1880b880-de49-11eb-88fb-4546654bf169.png)

![click_4_not_authorized_screen](https://user-images.githubusercontent.com/11938477/124622433-1dde0300-de49-11eb-8d10-022df37a7b29.png)

**Comment by b-solution** [comment]
@LAlexMHllc There is an authorize (before) action written in controller. I think it need to be skipped if the channel is public.

**Comment by b-solution** [comment]
For public channels only the creator can edit our delete the 'Dashboard', all other users only view it. 

<img width="1424" alt="Screenshot 2021-07-07 at 1 13 30 PM" src="https://user-images.githubusercontent.com/5988861/124724347-5d7a1d00-df25-11eb-9758-26a640751cd3.png">

<img width="1425" alt="Screenshot 2021-07-07 at 1 14 28 PM" src="https://user-images.githubusercontent.com/5988861/124724400-67038500-df25-11eb-99f6-a5982fbecc82.png">

And same with report only the creator or admin can delete it.
<img width="1438" alt="Screenshot 2021-07-07 at 1 16 49 PM" src="https://user-images.githubusercontent.com/5988861/124724754-b5b11f00-df25-11eb-99be-c099496c8c66.png">

We should consider this in 'connect report with dashboard' scenario too. 

I think only creator can connect report with only those dashboards which current user have access to edit. 

or do you want any user can share any report with any dashboard for public channel. Do let me know what you are thinking So that  I'll compete my work on it.

**Comment by bluenevus** [comment]
public reports are public for anyone else to do whatever.  Else its private to be shared or group to be shared with permissions assigned to it.

**Comment by LAlexMHllc** [comment]
Even when report creator clicks Connect button, the Not Authorized screen displayed.
Screenshot Example of Public Report

![connect_to_dashboards_clicked_on_public_channel_report](https://user-images.githubusercontent.com/11938477/130107161-c7c41309-b7f8-403d-bd6d-099c2cf91f18.png)

Screenshot Example of Not Authorized screen

![connect_to_dashboards_clicked_on_public_channel_report_not_authorized_screen_displayed](https://user-images.githubusercontent.com/11938477/130107326-aeffe919-0333-4ea2-ae13-289959c328ab.png)

**Comment by LAlexMHllc** [comment]
Reopening, since the issue still exists when user is not channel owner.
Screenshot Example

![public_channel_click_connect_with_dashboards](https://user-images.githubusercontent.com/11938477/140770423-c230033d-7cb7-42c4-8213-92287a99c5d2.png)

![public_channel_click_connect_with_dashboards_not_authorized](https://user-images.githubusercontent.com/11938477/140770445-853deca1-6d9a-45b6-9c1c-728a021b6be9.png)
