### ISSUE TITLE
the system shows duplicate groups

### ISSUE THREAD

**Issue by bluenevus** [MicroHealthLLC/mRMS#554]
There are duplicate groups but when I go in admin to find the duplicate group, I only see one of those groups

![image](https://user-images.githubusercontent.com/3675043/125084917-08aae380-e098-11eb-8448-ea4072df93eb.png)

under admin there is only one instance here

![image](https://user-images.githubusercontent.com/3675043/125085140-41e35380-e098-11eb-9757-9a4f2429d460.png)

**Comment by b-solution** [comment]
I'm trying to produce this issue, but did not succeed. 
1. create a group channel from admin user.
2. added this group channel in 2 different user.
3. Sign in to those user and check if it duplicate channel.

but it does not display duplicate channel. 

Can you explain your scenario as well so that I'll figure out this issue.

**Comment by b-solution** [comment]
@bluenevus I am not able to produced this issue, do you still facing this issue?

**Comment by bluenevus** [comment]
this is probably related to #643

**Comment by b-solution** [comment]
This is related to #643, which was closed and issue was resolved. So, I'm closing this one too.
